packages:
  - apps/web
  - apps/api
  - packages/db
  - packages/ui
  - packages/lib
  - packages/eslint-config
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - puppeteer
  - sharp
  - unrs-resolver
  - vue-demi
