# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


from typing_extensions import LiteralString
# -- template models.py.jinja --
from pydantic import BaseModel

from . import fields, actions
from ._types import FuncType
from ._builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class BaseLicense(_PrismaModel):
    __prisma_model__: ClassVar[Literal['License']] = 'License'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.LicenseActions[_PrismaModelT]':
        from .client import get_client

        return actions.LicenseActions[_PrismaModelT](client or get_client(), cls)


class BaseTenant(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Tenant']] = 'Tenant'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.TenantActions[_PrismaModelT]':
        from .client import get_client

        return actions.TenantActions[_PrismaModelT](client or get_client(), cls)


class BaseUserRole(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UserRole']] = 'UserRole'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserRoleActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserRoleActions[_PrismaModelT](client or get_client(), cls)


class BaseUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['User']] = 'User'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserActions[_PrismaModelT](client or get_client(), cls)


class BaseUserSession(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UserSession']] = 'UserSession'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserSessionActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserSessionActions[_PrismaModelT](client or get_client(), cls)


class BaseCandidate(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Candidate']] = 'Candidate'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CandidateActions[_PrismaModelT]':
        from .client import get_client

        return actions.CandidateActions[_PrismaModelT](client or get_client(), cls)


class BaseJob(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Job']] = 'Job'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.JobActions[_PrismaModelT]':
        from .client import get_client

        return actions.JobActions[_PrismaModelT](client or get_client(), cls)


class BaseJobCandidate(_PrismaModel):
    __prisma_model__: ClassVar[Literal['JobCandidate']] = 'JobCandidate'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.JobCandidateActions[_PrismaModelT]':
        from .client import get_client

        return actions.JobCandidateActions[_PrismaModelT](client or get_client(), cls)


class BaseProject(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Project']] = 'Project'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ProjectActions[_PrismaModelT]':
        from .client import get_client

        return actions.ProjectActions[_PrismaModelT](client or get_client(), cls)


class BaseAgent(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Agent']] = 'Agent'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AgentActions[_PrismaModelT]':
        from .client import get_client

        return actions.AgentActions[_PrismaModelT](client or get_client(), cls)


class BaseConversation(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Conversation']] = 'Conversation'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ConversationActions[_PrismaModelT]':
        from .client import get_client

        return actions.ConversationActions[_PrismaModelT](client or get_client(), cls)


class BaseAgentTask(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AgentTask']] = 'AgentTask'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AgentTaskActions[_PrismaModelT]':
        from .client import get_client

        return actions.AgentTaskActions[_PrismaModelT](client or get_client(), cls)


