# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


from typing_extensions import LiteralString
# -- template client.py.jinja --
import warnings
import logging
from datetime import timedelta
from pathlib import Path
from types import TracebackType
from typing_extensions import override

from pydantic import BaseModel

from . import types, models, errors, actions
from ._base_client import BasePrisma, UseClientDefault, USE_CLIENT_DEFAULT
from .types import DatasourceOverride, HttpConfig, MetricsFormat
from ._types import BaseModelT, PrismaMethod, TransactionId, Datasource
from .bases import _PrismaModel
from ._builder import QueryBuilder, dumps
from .generator.models import EngineType, OptionalValueFromEnvVar, BinaryPaths
from ._compat import removeprefix, model_parse
from ._constants import CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED, DEFAULT_CONNECT_TIMEOUT, DEFAULT_TX_MAX_WAIT, DEFAULT_TX_TIMEOUT
from ._raw_query import deserialize_raw_results
from ._metrics import Metrics
from .metadata import PRISMA_MODELS, RELATIONAL_FIELD_MAPPINGS
from ._transactions import AsyncTransactionManager, SyncTransactionManager

# re-exports
from ._base_client import SyncBasePrisma, AsyncBasePrisma, load_env as load_env
from ._registry import (
    register as register,
    get_client as get_client,
    RegisteredClient as RegisteredClient,
)


__all__ = (
    'ENGINE_TYPE',
    'SCHEMA_PATH',
    'BINARY_PATHS',
    'Batch',
    'Prisma',
    'Client',
    'load_env',
    'register',
    'get_client',
)

log: logging.Logger = logging.getLogger(__name__)

SCHEMA_PATH = Path('/Users/macanderson/Workspace/orchestrai/packages/db/schema.prisma')
PACKAGED_SCHEMA_PATH = Path(__file__).parent.joinpath('schema.prisma')
ENGINE_TYPE: EngineType = EngineType.binary
BINARY_PATHS = model_parse(BinaryPaths, {'queryEngine': {'darwin-arm64': '/Users/macanderson/.cache/prisma-python/binaries/5.17.0/393aa359c9ad4a4bb28630fb5613f9c281cde053/node_modules/prisma/query-engine-darwin-arm64'}, 'introspectionEngine': {}, 'migrationEngine': {}, 'libqueryEngine': {}, 'prismaFmt': {}})


class Prisma(AsyncBasePrisma):
    # Note: these property names can be customised using `/// @Python(instance_name: '...')`
    # https://prisma-client-py.readthedocs.io/en/stable/reference/schema-extensions/#instance_name
    license: 'actions.LicenseActions[models.License]'
    tenant: 'actions.TenantActions[models.Tenant]'
    userrole: 'actions.UserRoleActions[models.UserRole]'
    user: 'actions.UserActions[models.User]'
    usersession: 'actions.UserSessionActions[models.UserSession]'
    candidate: 'actions.CandidateActions[models.Candidate]'
    job: 'actions.JobActions[models.Job]'
    jobcandidate: 'actions.JobCandidateActions[models.JobCandidate]'
    project: 'actions.ProjectActions[models.Project]'
    agent: 'actions.AgentActions[models.Agent]'
    conversation: 'actions.ConversationActions[models.Conversation]'
    agenttask: 'actions.AgentTaskActions[models.AgentTask]'

    __slots__ = (
        'license',
        'tenant',
        'userrole',
        'user',
        'usersession',
        'candidate',
        'job',
        'jobcandidate',
        'project',
        'agent',
        'conversation',
        'agenttask',
    )

    def __init__(
        self,
        *,
        use_dotenv: bool = True,
        log_queries: bool = False,
        auto_register: bool = False,
        datasource: DatasourceOverride | None = None,
        connect_timeout: int | timedelta = DEFAULT_CONNECT_TIMEOUT,
        http: HttpConfig | None = None,
    ) -> None:
        super().__init__(
            http=http,
            use_dotenv=use_dotenv,
            log_queries=log_queries,
            datasource=datasource,
            connect_timeout=connect_timeout,
        )
        self._set_generated_properties(
            schema_path=SCHEMA_PATH,
            engine_type=ENGINE_TYPE,
            prisma_models=PRISMA_MODELS,
            packaged_schema_path=PACKAGED_SCHEMA_PATH,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
            preview_features=set(['multiSchema']),
            active_provider='postgresql',
            default_datasource_name='db',
        )

        self.license = actions.LicenseActions[models.License](self, models.License)
        self.tenant = actions.TenantActions[models.Tenant](self, models.Tenant)
        self.userrole = actions.UserRoleActions[models.UserRole](self, models.UserRole)
        self.user = actions.UserActions[models.User](self, models.User)
        self.usersession = actions.UserSessionActions[models.UserSession](self, models.UserSession)
        self.candidate = actions.CandidateActions[models.Candidate](self, models.Candidate)
        self.job = actions.JobActions[models.Job](self, models.Job)
        self.jobcandidate = actions.JobCandidateActions[models.JobCandidate](self, models.JobCandidate)
        self.project = actions.ProjectActions[models.Project](self, models.Project)
        self.agent = actions.AgentActions[models.Agent](self, models.Agent)
        self.conversation = actions.ConversationActions[models.Conversation](self, models.Conversation)
        self.agenttask = actions.AgentTaskActions[models.AgentTask](self, models.AgentTask)

        if auto_register:
            register(self)

    @property
    @override
    def _default_datasource(self) -> Datasource:
        return {
            'name': 'db',
            'url': OptionalValueFromEnvVar(**{'value': None, 'fromEnvVar': 'DATABASE_URL'}).resolve(),
            'source_file_path': '/Users/macanderson/Workspace/orchestrai/packages/db/schema.prisma',
        }

    async def execute_raw(self, query: LiteralString, *args: Any) -> int:
        resp = await self._execute(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=None,
        )
        return int(resp['data']['result'])

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> dict[str, Any]:
        ...

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> Optional[BaseModelT]:
        ...

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[Optional[BaseModelT], dict[str, Any]]:
        """This function is the exact same as `query_raw()` but returns the first result.

        If model is given, the returned record is converted to the pydantic model first,
        otherwise a raw dictionary will be returned.
        """
        results: Sequence[Union[BaseModelT, dict[str, Any]]]
        if model is not None:
            results = await self.query_raw(query, *args, model=model)
        else:
            results = await self.query_raw(query, *args)

        if not results:
            return None

        return results[0]

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[dict[str, Any]]:
        ...

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> List[BaseModelT]:
        ...

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[List[BaseModelT], List[dict[str, Any]]]:
        """Execute a raw SQL query against the database.

        If model is given, each returned record is converted to the pydantic model first,
        otherwise results will be raw dictionaries.
        """
        resp = await self._execute(
            method='query_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=model,
        )
        result = resp['data']['result']
        if model is not None:
            return deserialize_raw_results(result, model=model)

        return deserialize_raw_results(result)

    def batch_(self) -> Batch:
        """Returns a context manager for grouping write queries into a single transaction."""
        return Batch(client=self)

    def tx(
        self,
        *,
        max_wait: Union[int, timedelta] = DEFAULT_TX_MAX_WAIT,
        timeout: Union[int, timedelta] = DEFAULT_TX_TIMEOUT,
    ) -> TransactionManager:
        """Returns a context manager for executing queries within a database transaction.

        Entering the context manager returns a new Prisma instance wrapping all
        actions within a transaction, queries will be isolated to the Prisma instance and
        will not be commited to the database until the context manager exits.

        By default, Prisma will wait a maximum of 2 seconds to acquire a transaction from the database. You can modify this
        default with the `max_wait` argument which accepts a value in milliseconds or `datetime.timedelta`.

        By default, Prisma will cancel and rollback ay transactions that last longer than 5 seconds. You can modify this timeout
        with the `timeout` argument which accepts a value in milliseconds or `datetime.timedelta`.

        Example usage:

        ```py
        async with client.tx() as transaction:
            user1 = await client.user.create({'name': 'Robert'})
            user2 = await client.user.create({'name': 'Tegan'})
        ```

        In the above example, if the first database call succeeds but the second does not then neither of the records will be created.
        """
        return TransactionManager(
            client=self,
            max_wait=max_wait,
            timeout=timeout,
        )


TransactionManager = AsyncTransactionManager[Prisma]


# TODO: this should return the results as well
# TODO: don't require copy-pasting arguments between actions and batch actions
class Batch:
    license: 'LicenseBatchActions'
    tenant: 'TenantBatchActions'
    userrole: 'UserRoleBatchActions'
    user: 'UserBatchActions'
    usersession: 'UserSessionBatchActions'
    candidate: 'CandidateBatchActions'
    job: 'JobBatchActions'
    jobcandidate: 'JobCandidateBatchActions'
    project: 'ProjectBatchActions'
    agent: 'AgentBatchActions'
    conversation: 'ConversationBatchActions'
    agenttask: 'AgentTaskBatchActions'

    def __init__(self, client: Prisma) -> None:
        self.__client = client
        self.__queries: List[str] = []
        self._active_provider = client._active_provider
        self.license = LicenseBatchActions(self)
        self.tenant = TenantBatchActions(self)
        self.userrole = UserRoleBatchActions(self)
        self.user = UserBatchActions(self)
        self.usersession = UserSessionBatchActions(self)
        self.candidate = CandidateBatchActions(self)
        self.job = JobBatchActions(self)
        self.jobcandidate = JobCandidateBatchActions(self)
        self.project = ProjectBatchActions(self)
        self.agent = AgentBatchActions(self)
        self.conversation = ConversationBatchActions(self)
        self.agenttask = AgentTaskBatchActions(self)

    def _add(self, **kwargs: Any) -> None:
        builder = QueryBuilder(
            **kwargs,
            prisma_models=PRISMA_MODELS,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
        )
        self.__queries.append(builder.build_query())

    async def commit(self) -> None:
        """Execute the queries"""
        # TODO: normalise this, we should still call client._execute
        queries = self.__queries
        self.__queries = []

        payload = {
            'batch': [
                {
                    'query': query,
                    'variables': {},
                }
                for query in queries
            ],
            'transaction': True,
        }
        await self.__client._engine.query(
            dumps(payload),
            tx_id=self.__client._tx_id,
        )

    def execute_raw(self, query: LiteralString, *args: Any) -> None:
        self._add(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            }
        )

    async def __aenter__(self) -> 'Batch':
        return self

    async def __aexit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> None:
        if exc is None:
            await self.commit()


# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class LicenseBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.LicenseCreateInput,
        include: Optional[types.LicenseInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.License,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.LicenseCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.License,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.LicenseWhereUniqueInput,
        include: Optional[types.LicenseInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.License,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.LicenseUpdateInput,
        where: types.LicenseWhereUniqueInput,
        include: Optional[types.LicenseInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.License,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.LicenseWhereUniqueInput,
        data: types.LicenseUpsertInput,
        include: Optional[types.LicenseInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.License,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.LicenseUpdateManyMutationInput,
        where: types.LicenseWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.License,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.LicenseWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.License,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class TenantBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.TenantCreateInput,
        include: Optional[types.TenantInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Tenant,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.TenantCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Tenant,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.TenantWhereUniqueInput,
        include: Optional[types.TenantInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Tenant,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.TenantUpdateInput,
        where: types.TenantWhereUniqueInput,
        include: Optional[types.TenantInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Tenant,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.TenantWhereUniqueInput,
        data: types.TenantUpsertInput,
        include: Optional[types.TenantInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Tenant,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.TenantUpdateManyMutationInput,
        where: types.TenantWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Tenant,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.TenantWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Tenant,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserRoleBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserRoleCreateInput,
        include: Optional[types.UserRoleInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.UserRole,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserRoleCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.UserRole,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserRoleWhereUniqueInput,
        include: Optional[types.UserRoleInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.UserRole,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserRoleUpdateInput,
        where: types.UserRoleWhereUniqueInput,
        include: Optional[types.UserRoleInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.UserRole,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserRoleWhereUniqueInput,
        data: types.UserRoleUpsertInput,
        include: Optional[types.UserRoleInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.UserRole,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserRoleUpdateManyMutationInput,
        where: types.UserRoleWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.UserRole,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserRoleWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.UserRole,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserCreateInput,
        include: Optional[types.UserInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.User,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.User,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserWhereUniqueInput,
        include: Optional[types.UserInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.User,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserUpdateInput,
        where: types.UserWhereUniqueInput,
        include: Optional[types.UserInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.User,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserWhereUniqueInput,
        data: types.UserUpsertInput,
        include: Optional[types.UserInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.User,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserUpdateManyMutationInput,
        where: types.UserWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.User,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.User,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserSessionBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserSessionCreateInput,
        include: Optional[types.UserSessionInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.UserSession,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserSessionCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.UserSession,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserSessionWhereUniqueInput,
        include: Optional[types.UserSessionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.UserSession,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserSessionUpdateInput,
        where: types.UserSessionWhereUniqueInput,
        include: Optional[types.UserSessionInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.UserSession,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserSessionWhereUniqueInput,
        data: types.UserSessionUpsertInput,
        include: Optional[types.UserSessionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.UserSession,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserSessionUpdateManyMutationInput,
        where: types.UserSessionWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.UserSession,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserSessionWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.UserSession,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class CandidateBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.CandidateCreateInput,
        include: Optional[types.CandidateInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Candidate,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.CandidateCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Candidate,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.CandidateWhereUniqueInput,
        include: Optional[types.CandidateInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Candidate,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.CandidateUpdateInput,
        where: types.CandidateWhereUniqueInput,
        include: Optional[types.CandidateInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Candidate,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.CandidateWhereUniqueInput,
        data: types.CandidateUpsertInput,
        include: Optional[types.CandidateInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Candidate,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.CandidateUpdateManyMutationInput,
        where: types.CandidateWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Candidate,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.CandidateWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Candidate,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class JobBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.JobCreateInput,
        include: Optional[types.JobInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Job,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.JobCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Job,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.JobWhereUniqueInput,
        include: Optional[types.JobInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Job,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.JobUpdateInput,
        where: types.JobWhereUniqueInput,
        include: Optional[types.JobInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Job,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.JobWhereUniqueInput,
        data: types.JobUpsertInput,
        include: Optional[types.JobInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Job,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.JobUpdateManyMutationInput,
        where: types.JobWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Job,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.JobWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Job,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class JobCandidateBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.JobCandidateCreateInput,
        include: Optional[types.JobCandidateInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.JobCandidate,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.JobCandidateCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.JobCandidate,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.JobCandidateWhereUniqueInput,
        include: Optional[types.JobCandidateInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.JobCandidate,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.JobCandidateUpdateInput,
        where: types.JobCandidateWhereUniqueInput,
        include: Optional[types.JobCandidateInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.JobCandidate,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.JobCandidateWhereUniqueInput,
        data: types.JobCandidateUpsertInput,
        include: Optional[types.JobCandidateInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.JobCandidate,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.JobCandidateUpdateManyMutationInput,
        where: types.JobCandidateWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.JobCandidate,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.JobCandidateWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.JobCandidate,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class ProjectBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.ProjectCreateInput,
        include: Optional[types.ProjectInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Project,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.ProjectCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Project,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.ProjectWhereUniqueInput,
        include: Optional[types.ProjectInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Project,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.ProjectUpdateInput,
        where: types.ProjectWhereUniqueInput,
        include: Optional[types.ProjectInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Project,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.ProjectWhereUniqueInput,
        data: types.ProjectUpsertInput,
        include: Optional[types.ProjectInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Project,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.ProjectUpdateManyMutationInput,
        where: types.ProjectWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Project,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.ProjectWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Project,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class AgentBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.AgentCreateInput,
        include: Optional[types.AgentInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Agent,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.AgentCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Agent,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.AgentWhereUniqueInput,
        include: Optional[types.AgentInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Agent,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.AgentUpdateInput,
        where: types.AgentWhereUniqueInput,
        include: Optional[types.AgentInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Agent,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.AgentWhereUniqueInput,
        data: types.AgentUpsertInput,
        include: Optional[types.AgentInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Agent,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.AgentUpdateManyMutationInput,
        where: types.AgentWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Agent,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.AgentWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Agent,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class ConversationBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.ConversationCreateInput,
        include: Optional[types.ConversationInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Conversation,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.ConversationCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Conversation,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.ConversationWhereUniqueInput,
        include: Optional[types.ConversationInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Conversation,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.ConversationUpdateInput,
        where: types.ConversationWhereUniqueInput,
        include: Optional[types.ConversationInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Conversation,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.ConversationWhereUniqueInput,
        data: types.ConversationUpsertInput,
        include: Optional[types.ConversationInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Conversation,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.ConversationUpdateManyMutationInput,
        where: types.ConversationWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Conversation,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.ConversationWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Conversation,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class AgentTaskBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.AgentTaskCreateInput,
        include: Optional[types.AgentTaskInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.AgentTask,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.AgentTaskCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.AgentTask,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.AgentTaskWhereUniqueInput,
        include: Optional[types.AgentTaskInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.AgentTask,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.AgentTaskUpdateInput,
        where: types.AgentTaskWhereUniqueInput,
        include: Optional[types.AgentTaskInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.AgentTask,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.AgentTaskWhereUniqueInput,
        data: types.AgentTaskUpsertInput,
        include: Optional[types.AgentTaskInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.AgentTask,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.AgentTaskUpdateManyMutationInput,
        where: types.AgentTaskWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.AgentTask,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.AgentTaskWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.AgentTask,
            arguments={'where': where},
            root_selection=['count'],
        )



Client = Prisma