# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


from typing_extensions import LiteralString
# -- template enums.py.jinja --
from ._compat import StrEnum


class LicenseType(StrEnum):
    FREE = 'FREE'
    BASIC = 'BASIC'
    PRO = 'PRO'
    ENTERPRISE = 'ENTERPRISE'
    CUSTOM = 'CUSTOM'

class UserRoleType(StrEnum):
    BUSINESS_ADMIN = 'BUSINESS_ADMIN'
    BUSINESS_USER = 'BUSINESS_USER'
    CUSTOMER_ADMIN = 'CUSTOMER_ADMIN'
    CUSTOMER_USER = 'CUSTOMER_USER'

class CareerLevel(StrEnum):
    ENTRY = 'ENTRY'
    MID = 'MID'
    SENIOR = 'SENIOR'
    EXECUTIVE = 'EXECUTIVE'

class EducationLevel(StrEnum):
    HIGH_SCHOOL = 'HIGH_SCHOOL'
    ASSOCIATE = 'ASSOCIATE'
    BACHELOR = 'BACHELOR'
    MASTER = 'MASTER'
    PHD = 'PHD'

class CandidateStatus(StrEnum):
    ACTIVE = 'ACTIVE'
    INACTIVE = 'INACTIVE'
    HIRED = 'HIRED'
    REJECTED = 'REJECTED'

class CandidateSource(StrEnum):
    ADVERTISING = 'ADVERTISING'
    COLD_CALL = 'COLD_CALL'
    EVENT = 'EVENT'
    GITHUB = 'GITHUB'
    JOB_BOARD = 'JOB_BOARD'
    JOB_FAIR = 'JOB_FAIR'
    LINKEDIN = 'LINKEDIN'
    OTHER = 'OTHER'
    REFERRAL = 'REFERRAL'
    SOCIAL_MEDIA = 'SOCIAL_MEDIA'
    UNKNOWN = 'UNKNOWN'
    WEBSITE = 'WEBSITE'

class JobStatus(StrEnum):
    DRAFT = 'DRAFT'
    OPEN = 'OPEN'
    FILLED = 'FILLED'
    CANCELLED = 'CANCELLED'

class AgentType(StrEnum):
    ASSISTANT = 'ASSISTANT'
    DISPATCHER = 'DISPATCHER'
    DATA_PROCESSOR = 'DATA_PROCESSOR'
    SQL_RUNNER = 'SQL_RUNNER'
    WEB_SCRAPER = 'WEB_SCRAPER'
    SENTIMENT_ANALYZER = 'SENTIMENT_ANALYZER'
    RECOMMENDER = 'RECOMMENDER'
    REPORT_BUILDER = 'REPORT_BUILDER'
    EMAIL_GENERATOR = 'EMAIL_GENERATOR'
    SMS_GENERATOR = 'SMS_GENERATOR'
    SCHEDULER = 'SCHEDULER'
    TASK_MANAGER = 'TASK_MANAGER'

