from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'License',
    'Tenant',
    'UserRole',
    'User',
    'UserSession',
    'Candidate',
    'Job',
    'JobCandidate',
    'Project',
    'Agent',
    'Conversation',
    'AgentTask',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'License': {
        'tenants': 'Tenant',
    },
    'Tenant': {
        'users': 'User',
        'projects': 'Project',
        'jobs': 'Job',
        'agents': 'Agent',
        'candidates': 'Candidate',
        'license': 'License',
    },
    'UserRole': {
        'users': 'User',
    },
    'User': {
        'role': 'UserRole',
        'tenant': 'Tenant',
        'projects': 'Project',
        'sessions': 'UserSession',
    },
    'UserSession': {
        'user': 'User',
    },
    'Candidate': {
        'jobCandidates': 'JobCandidate',
        'tenant': 'Tenant',
    },
    'Job': {
        'tenant': 'Tenant',
        'jobCandidates': 'JobCandidate',
    },
    'JobCandidate': {
        'job': 'Job',
        'candidate': 'Candidate',
    },
    'Project': {
        'tenant': 'Tenant',
        'user': 'User',
    },
    'Agent': {
        'tenant': 'Tenant',
        'conversations': 'Conversation',
        'agentTasks': 'AgentTask',
    },
    'Conversation': {
        'agent': 'Agent',
        'agentTasks': 'AgentTask',
    },
    'AgentTask': {
        'agent': 'Agent',
        'conversation': 'Conversation',
    },
}

# fmt: on